# Generated by Django 3.1.3 on 2020-12-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docscanner', '0002_auto_20201209_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='docList',
        ),
    ]
