# Generated by Django 3.1.3 on 2020-12-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('docscanner', '0003_remove_group_doclist'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nrPages',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
