# Generated by Django 3.1.3 on 2020-12-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docscanner', '0004_group_nrpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scanningDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
